import {
  ROULETTE_PRIZE_COLOR_ENUM,
  ROULETTE_PRIZE_OPTION_TITLE_ENUM,
  ROULETTE_PRIZE_OPTIONS_ENUM,
  RouletteOption,
} from '../types'
export const rouletteOptions: RouletteOption[] = [
  {
    option: ROULETTE_PRIZE_OPTION_TITLE_ENUM.X20,
    prize: ROULETTE_PRIZE_OPTIONS_ENUM.X20,
    style: { backgroundColor: ROULETTE_PRIZE_COLOR_ENUM.X20 },
    title: '20',
  },
  {
    option: ROULETTE_PRIZE_OPTION_TITLE_ENUM.X1,
    prize: ROULETTE_PRIZE_OPTIONS_ENUM.X1,
    style: { backgroundColor: ROULETTE_PRIZE_COLOR_ENUM.X1 },
    title: '1',
  },
  {
    option: ROULETTE_PRIZE_OPTION_TITLE_ENUM.X5,
    prize: ROULETTE_PRIZE_OPTIONS_ENUM.X5,
    style: { backgroundColor: ROULETTE_PRIZE_COLOR_ENUM.X5 },
    title: '5',
  },
  {
    option: ROULETTE_PRIZE_OPTION_TITLE_ENUM.X1,
    prize: ROULETTE_PRIZE_OPTIONS_ENUM.X1,
    style: { backgroundColor: ROULETTE_PRIZE_COLOR_ENUM.X1 },
    title: '1',
  },
  {
    option: ROULETTE_PRIZE_OPTION_TITLE_ENUM.X3,
    prize: ROULETTE_PRIZE_OPTIONS_ENUM.X3,
    style: { backgroundColor: ROULETTE_PRIZE_COLOR_ENUM.X3 },
    title: '3',
  },
  {
    option: ROULETTE_PRIZE_OPTION_TITLE_ENUM.X1,
    prize: ROULETTE_PRIZE_OPTIONS_ENUM.X1,
    style: { backgroundColor: ROULETTE_PRIZE_COLOR_ENUM.X1 },
    title: '1',
  },
  {
    option: ROULETTE_PRIZE_OPTION_TITLE_ENUM.X10,
    prize: ROULETTE_PRIZE_OPTIONS_ENUM.X10,
    style: { backgroundColor: ROULETTE_PRIZE_COLOR_ENUM.X10 },
    title: '10',
  },
  {
    option: ROULETTE_PRIZE_OPTION_TITLE_ENUM.X1,
    prize: ROULETTE_PRIZE_OPTIONS_ENUM.X1,
    style: { backgroundColor: ROULETTE_PRIZE_COLOR_ENUM.X1 },
    title: '1',
  },
  {
    option: ROULETTE_PRIZE_OPTION_TITLE_ENUM.X3,
    prize: ROULETTE_PRIZE_OPTIONS_ENUM.X3,
    style: { backgroundColor: ROULETTE_PRIZE_COLOR_ENUM.X3 },
    title: '3',
  },
  {
    option: ROULETTE_PRIZE_OPTION_TITLE_ENUM.X1,
    prize: ROULETTE_PRIZE_OPTIONS_ENUM.X1,
    style: { backgroundColor: ROULETTE_PRIZE_COLOR_ENUM.X1 },
    title: '1',
  },
  {
    option: ROULETTE_PRIZE_OPTION_TITLE_ENUM.X5,
    prize: ROULETTE_PRIZE_OPTIONS_ENUM.X5,
    style: { backgroundColor: ROULETTE_PRIZE_COLOR_ENUM.X5 },
    title: '5',
  },
  {
    option: ROULETTE_PRIZE_OPTION_TITLE_ENUM.X1,
    prize: ROULETTE_PRIZE_OPTIONS_ENUM.X1,
    style: { backgroundColor: ROULETTE_PRIZE_COLOR_ENUM.X1 },
    title: '1',
  },
  {
    option: ROULETTE_PRIZE_OPTION_TITLE_ENUM.X10,
    prize: ROULETTE_PRIZE_OPTIONS_ENUM.X10,
    style: { backgroundColor: ROULETTE_PRIZE_COLOR_ENUM.X10 },
    title: '10',
  },
  {
    option: ROULETTE_PRIZE_OPTION_TITLE_ENUM.X1,
    prize: ROULETTE_PRIZE_OPTIONS_ENUM.X1,
    style: { backgroundColor: ROULETTE_PRIZE_COLOR_ENUM.X1 },
    title: '1',
  },
  {
    option: ROULETTE_PRIZE_OPTION_TITLE_ENUM.X3,
    prize: ROULETTE_PRIZE_OPTIONS_ENUM.X3,
    style: { backgroundColor: ROULETTE_PRIZE_COLOR_ENUM.X3 },
    title: '3',
  },
  {
    option: ROULETTE_PRIZE_OPTION_TITLE_ENUM.X1,
    prize: ROULETTE_PRIZE_OPTIONS_ENUM.X1,
    style: { backgroundColor: ROULETTE_PRIZE_COLOR_ENUM.X1 },
    title: '1',
  },
  {
    option: ROULETTE_PRIZE_OPTION_TITLE_ENUM.X5,
    prize: ROULETTE_PRIZE_OPTIONS_ENUM.X5,
    style: { backgroundColor: ROULETTE_PRIZE_COLOR_ENUM.X5 },
    title: '5',
  },
  {
    option: ROULETTE_PRIZE_OPTION_TITLE_ENUM.X1,
    prize: ROULETTE_PRIZE_OPTIONS_ENUM.X1,
    style: { backgroundColor: ROULETTE_PRIZE_COLOR_ENUM.X1 },
    title: '1',
  },
  {
    option: ROULETTE_PRIZE_OPTION_TITLE_ENUM.X3,
    prize: ROULETTE_PRIZE_OPTIONS_ENUM.X3,
    style: { backgroundColor: ROULETTE_PRIZE_COLOR_ENUM.X3 },
    title: '3',
  },
  {
    option: ROULETTE_PRIZE_OPTION_TITLE_ENUM.X1,
    prize: ROULETTE_PRIZE_OPTIONS_ENUM.X1,
    style: { backgroundColor: ROULETTE_PRIZE_COLOR_ENUM.X1 },
    title: '1',
  },
]
