import { PRIZE_COLOR_ENUM, PRIZE_OPTION_TITLE_ENUM, PRIZE_OPTIONS_ENUM, RouletteOption } from '../types'
export const rouletteOptions: RouletteOption[] = [
  {
    option: PRIZE_OPTION_TITLE_ENUM.X3,
    prize: PRIZE_OPTIONS_ENUM.X3,
    style: { backgroundColor: PRIZE_COLOR_ENUM.X3 },
    title: '3',
  },
  {
    option: PRIZE_OPTION_TITLE_ENUM.X1,
    prize: PRIZE_OPTIONS_ENUM.X1,
    style: { backgroundColor: PRIZE_COLOR_ENUM.X1 },
    title: '1',
  },
  {
    option: PRIZE_OPTION_TITLE_ENUM.X5,
    prize: PRIZE_OPTIONS_ENUM.X5,
    style: { backgroundColor: PRIZE_COLOR_ENUM.X5 },
    title: '5',
  },
  {
    option: PRIZE_OPTION_TITLE_ENUM.X1,
    prize: PRIZE_OPTIONS_ENUM.X1,
    style: { backgroundColor: PRIZE_COLOR_ENUM.X1 },
    title: '1',
  },
  {
    option: PRIZE_OPTION_TITLE_ENUM.X3,
    prize: PRIZE_OPTIONS_ENUM.X3,
    style: { backgroundColor: PRIZE_COLOR_ENUM.X3 },
    title: '3',
  },
  {
    option: PRIZE_OPTION_TITLE_ENUM.X1,
    prize: PRIZE_OPTIONS_ENUM.X1,
    style: { backgroundColor: PRIZE_COLOR_ENUM.X1 },
    title: '1',
  },
  {
    option: PRIZE_OPTION_TITLE_ENUM.X10,
    prize: PRIZE_OPTIONS_ENUM.X10,
    style: { backgroundColor: PRIZE_COLOR_ENUM.X10 },
    title: '10',
  },
  {
    option: PRIZE_OPTION_TITLE_ENUM.X1,
    prize: PRIZE_OPTIONS_ENUM.X1,
    style: { backgroundColor: PRIZE_COLOR_ENUM.X1 },
    title: '1',
  },
  {
    option: PRIZE_OPTION_TITLE_ENUM.X5,
    prize: PRIZE_OPTIONS_ENUM.X5,
    style: { backgroundColor: PRIZE_COLOR_ENUM.X5 },
    title: '5',
  },
  {
    option: PRIZE_OPTION_TITLE_ENUM.X3,
    prize: PRIZE_OPTIONS_ENUM.X3,
    style: { backgroundColor: PRIZE_COLOR_ENUM.X3 },
    title: '3',
  },
  {
    option: PRIZE_OPTION_TITLE_ENUM.X1,
    prize: PRIZE_OPTIONS_ENUM.X1,
    style: { backgroundColor: PRIZE_COLOR_ENUM.X1 },
    title: '1',
  },
  {
    option: PRIZE_OPTION_TITLE_ENUM.X3,
    prize: PRIZE_OPTIONS_ENUM.X3,
    style: { backgroundColor: PRIZE_COLOR_ENUM.X3 },
    title: '3',
  },
  {
    option: PRIZE_OPTION_TITLE_ENUM.X5,
    prize: PRIZE_OPTIONS_ENUM.X5,
    style: { backgroundColor: PRIZE_COLOR_ENUM.X5 },
    title: '5',
  },
  {
    option: PRIZE_OPTION_TITLE_ENUM.X1,
    prize: PRIZE_OPTIONS_ENUM.X1,
    style: { backgroundColor: PRIZE_COLOR_ENUM.X1 },
    title: '1',
  },
  {
    option: PRIZE_OPTION_TITLE_ENUM.X20,
    prize: PRIZE_OPTIONS_ENUM.X20,
    style: { backgroundColor: PRIZE_COLOR_ENUM.X20 },
    title: '20',
  },
  {
    option: PRIZE_OPTION_TITLE_ENUM.X3,
    prize: PRIZE_OPTIONS_ENUM.X3,
    style: { backgroundColor: PRIZE_COLOR_ENUM.X3 },
    title: '3',
  },
  {
    option: PRIZE_OPTION_TITLE_ENUM.X1,
    prize: PRIZE_OPTIONS_ENUM.X1,
    style: { backgroundColor: PRIZE_COLOR_ENUM.X1 },
    title: '1',
  },
  {
    option: PRIZE_OPTION_TITLE_ENUM.X5,
    prize: PRIZE_OPTIONS_ENUM.X5,
    style: { backgroundColor: PRIZE_COLOR_ENUM.X5 },
    title: '5',
  },
  {
    option: PRIZE_OPTION_TITLE_ENUM.X10,
    prize: PRIZE_OPTIONS_ENUM.X10,
    style: { backgroundColor: PRIZE_COLOR_ENUM.X10 },
    title: '10',
  },
  {
    option: PRIZE_OPTION_TITLE_ENUM.X1,
    prize: PRIZE_OPTIONS_ENUM.X1,
    style: { backgroundColor: PRIZE_COLOR_ENUM.X1 },
    title: '1',
  },
]
